name: Dotnet Unit Tests

on:
  push:
    branches:
      - '**'    
      - '!main'
    paths:
      - dotnet/**
      - .github/workflows/dotnet-unit-tests.yml
  workflow_dispatch:

env:
  CSPROJ_PATH: 'dotnet/Ripe.Sdk.Tests'
  DOTNET_VERSION: '8.0.x' 

jobs:
  run-dotnet-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Install dependencies'
        shell: pwsh
        run: |
          cd ${{ env.CSPROJ_PATH }}
          dotnet restore
      - name: 'Build'
        shell: pwsh
        run: |
          cd ${{ env.CSPROJ_PATH }}
          dotnet build
      - name: 'Test'
        shell: pwsh
        run: |
          cd ${{ env.CSPROJ_PATH }}
          dotnet test