name: Publish to NPM 

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - node/ripesdk/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build
        run: npm ci && npm run
        working-directory: ./node/ripesdk/
      - name: Publish package on NPM
        run: npm publish
        working-directory: ./node/ripesdk/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
