name: NuGet Publish Core

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

env:
  ENV_PROJECT_CORE: '/Ripe.Sdk.Core'

jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    name: Publish NuGet Package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: ${{ secrets.NUGET_SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd ${{ env.ENV_PROJECT_CORE }}
          dotnet pack -c Release -o out  

      - name: Push generated package to nuget registry
        run: |
          dotnet nuget push ./${{ env.ENV_PROJECT_CORE }}/out/*.nupkg --skip-duplicate --no-symbols true